// libs/helix-react/src/sidebar/MenuBadge.tsx
// libs/helix-react/src/sidebar/MenuBadge.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/helix';

export function MenuBadge({ className, ...props }: HTMLArkProps<'div'>) {
  return (
    <ark.div
      data-slot="sidebar-menu-badge"
      data-sidebar="menu-badge"
      className={cn(sidebarStyles.menuBadgeClass, className)}
      {...props}
    />
  );
}

// libs/helix-svelte/src/sidebar/MenuBadge.svelte
<!-- libs/helix-svelte/src/SidebarMenuBadge.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="div"
  data-slot="sidebar-menu-badge"
  data-sidebar="menu-badge"
  class={cn(sidebarStyles.menuBadgeClass, className)}
  {...rest}
>
  {@render children?.()}
</Ark>
