// libs/vortex-svelte/src/sidebar/Rail.svelte
<!-- libs/vortex-svelte/src/SidebarRail.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';
  import { getSidebarContext } from './context.svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
  } & HTMLButtonAttributes;

  let { class: className = '', onclick, ...rest }: Props = $props();

  const { toggleSidebar } = getSidebarContext();
</script>

<Ark
  as="button"
  data-sidebar="rail"
  data-slot="sidebar-rail"
  type="button"
  aria-label="Toggle Sidebar"
  tabindex={-1}
  title="Toggle Sidebar"
  class={cn(sidebarStyles.railClass, className)}
  onclick={(e) => {
    onclick?.(e);
    toggleSidebar();
  }}
  {...rest}
/>

// libs/vortex-react/src/sidebar/Rail.tsx
// libs/vortex-react/src/sidebar/Rail.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';
import { useSidebar } from './context';

export function Rail({ className, ...props }: HTMLArkProps<'button'>) {
  const { toggleSidebar } = useSidebar();

  return (
    <ark.button
      data-sidebar="rail"
      data-slot="sidebar-rail"
      type="button"
      aria-label="Toggle Sidebar"
      tabIndex={-1}
      onClick={toggleSidebar}
      title="Toggle Sidebar"
      className={cn(sidebarStyles.railClass, className)}
      {...props}
    />
  );
}
