// libs/wicn-react/src/sidebar/Menu.tsx
// libs/wicn-react/src/sidebar/Menu.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from 'wicn-core';

export function Menu({ className, ...props }: HTMLArkProps<'ul'>) {
  return (
    <ark.ul
      data-slot="sidebar-menu"
      data-sidebar="menu"
      className={cn(sidebarStyles.menuClass, className)}
      {...props}
    />
  );
}

// libs/wicn-svelte/src/sidebar/Menu.svelte
<!-- libs/wicn-svelte/src/SidebarMenu.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from wicn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from 'wicn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLUListElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark as="ul" data-slot="sidebar-menu" data-sidebar="menu" class={cn(sidebarStyles.menuClass, className)} {...rest}>
  {@render children?.()}
</Ark>
