// libs/helix-react/src/checkbox.tsx
// libs/helix-react/src/checkbox.tsx
// Closely based on: Shark UI checkbox (@ark-ui/react/checkbox)
import { createContext, useContext } from 'react';
import {
  CheckboxRoot as ArkCheckboxRoot,
  CheckboxControl as ArkCheckboxControl,
  CheckboxIndicator as ArkCheckboxIndicator,
  CheckboxLabel as ArkCheckboxLabel,
  CheckboxGroup as ArkCheckboxGroup,
  CheckboxHiddenInput as ArkCheckboxHiddenInput,
  useCheckboxContext,
  type CheckboxRootProps,
} from '@ark-ui/react/checkbox';
import type { CheckboxControlProps, CheckboxIndicatorProps, CheckboxLabelProps, CheckboxGroupProps } from '@ark-ui/react/checkbox';
import { checkboxVariants, checkboxIndicatorBase, checkboxLabelBase, checkboxGroupBase, cn } from '@cloudvoyant/helix';
import type { CheckboxProps as CheckboxBaseProps } from '@cloudvoyant/helix';

export type CheckboxProps = CheckboxRootProps & CheckboxBaseProps;

const CheckboxSizeContext = createContext<CheckboxBaseProps['size']>('md');

export function Checkbox({ className, size = 'md', children, ...props }: CheckboxProps) {
  return (
    <CheckboxSizeContext.Provider value={size}>
      <ArkCheckboxRoot className={cn('flex items-center gap-2', className)} {...props}>
        {children}
        <ArkCheckboxHiddenInput />
      </ArkCheckboxRoot>
    </CheckboxSizeContext.Provider>
  );
}

export function CheckboxControl({ className, ...props }: CheckboxControlProps) {
  const size = useContext(CheckboxSizeContext);
  return <ArkCheckboxControl className={cn(checkboxVariants({ size }), className)} {...props} />;
}

export function CheckboxIndicator({ className, ...props }: CheckboxIndicatorProps) {
  return <ArkCheckboxIndicator className={cn(checkboxIndicatorBase, className)} {...props} />;
}

export function CheckboxLabel({ className, ...props }: CheckboxLabelProps) {
  return <ArkCheckboxLabel className={cn(checkboxLabelBase, className)} {...props} />;
}

export function CheckboxGroup({ className, ...props }: CheckboxGroupProps) {
  return <ArkCheckboxGroup className={cn(checkboxGroupBase, className)} {...props} />;
}

export const useCheckbox = useCheckboxContext;

export type { CheckboxControlProps, CheckboxIndicatorProps, CheckboxLabelProps, CheckboxGroupProps };

// libs/helix-svelte/src/checkbox/Checkbox.svelte
<!-- libs/helix-svelte/src/checkbox/Checkbox.svelte -->
<!-- Closely based on: Shark UI checkbox (@ark-ui/svelte/checkbox), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { setContext } from 'svelte';
  import { CheckboxRoot, CheckboxHiddenInput, type CheckboxRootProps } from '@ark-ui/svelte/checkbox';
  import { cn } from '@cloudvoyant/helix';

  type Props = CheckboxRootProps & {
    size?: 'sm' | 'md' | 'lg';
    class?: string;
  };

  let { size = 'md', class: className = '', children, ...rest }: Props = $props();

  setContext<'sm' | 'md' | 'lg'>('checkbox-size', size);

  const classes = $derived(cn('flex items-center gap-2', className));
</script>

<CheckboxRoot class={classes} {...rest}>
  {@render children?.()}
  <CheckboxHiddenInput />
</CheckboxRoot>
