// libs/helix-svelte/src/Scroll.svelte
<!-- libs/helix-svelte/src/Scroll.svelte -->
<!-- Closely based on: @ark-ui/svelte/scroll-area (Ark UI), Chakra UI ScrollArea, mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import {
    ScrollAreaRoot,
    ScrollAreaViewport,
    ScrollAreaContent,
    ScrollAreaScrollbar,
    ScrollAreaThumb,
    ScrollAreaCorner,
  } from '@ark-ui/svelte/scroll-area';
  import type { ScrollAreaRootProps } from '@ark-ui/svelte/scroll-area';
  import {
    scrollRootBase,
    scrollViewportBase,
    scrollContentBase,
    scrollScrollbarBase,
    scrollThumbBase,
    scrollCornerBase,
    cn,
  } from '@cloudvoyant/helix';

  type Props = ScrollAreaRootProps & {
    orientation?: 'vertical' | 'horizontal' | 'both';
    /** `default` shows the styled scrollbars; `hidden` keeps scrolling without rendering any scrollbar. */
    variant?: 'default' | 'hidden';
    contentClass?: string;
    thumbClass?: string;
    /** Overrides the viewport class. The default is `flex h-full w-full flex-col`;
     * for horizontal scrolling wrap content in a flex row or override this. */
    viewportClass?: string;
  };

  let {
    class: className = '',
    orientation = 'vertical',
    variant = 'default',
    contentClass = '',
    thumbClass = '',
    viewportClass = '',
    children,
    ...rest
  }: Props = $props();

  const rootClasses = $derived(cn(scrollRootBase, className));
  const viewportClasses = $derived(cn(scrollViewportBase, viewportClass));
  const contentClasses = $derived(cn(scrollContentBase, contentClass));
  const thumbClasses = $derived(cn(scrollThumbBase, thumbClass));
</script>

<ScrollAreaRoot class={rootClasses} {...rest}>
  <ScrollAreaViewport class={viewportClasses}>
    <ScrollAreaContent class={contentClasses}>
      {@render children?.()}
    </ScrollAreaContent>
  </ScrollAreaViewport>
  {#if variant !== 'hidden'}
    {#if orientation === 'vertical' || orientation === 'both'}
      <ScrollAreaScrollbar orientation="vertical" class={scrollScrollbarBase}>
        <ScrollAreaThumb class={thumbClasses} />
      </ScrollAreaScrollbar>
    {/if}
    {#if orientation === 'horizontal' || orientation === 'both'}
      <ScrollAreaScrollbar orientation="horizontal" class={scrollScrollbarBase}>
        <ScrollAreaThumb class={thumbClasses} />
      </ScrollAreaScrollbar>
    {/if}
    {#if orientation === 'both'}
      <ScrollAreaCorner class={scrollCornerBase} />
    {/if}
  {/if}
</ScrollAreaRoot>

// libs/helix-react/src/scroll.tsx
// libs/helix-react/src/scroll.tsx
// Closely based on: @ark-ui/react/scroll-area (Ark UI), Chakra UI ScrollArea
import {
  ScrollAreaRoot as ArkRoot,
  ScrollAreaViewport as ArkViewport,
  ScrollAreaContent as ArkContent,
  ScrollAreaScrollbar as ArkScrollbar,
  ScrollAreaThumb as ArkThumb,
  ScrollAreaCorner as ArkCorner,
  type ScrollAreaRootProps,
} from '@ark-ui/react/scroll-area';
import {
  scrollRootBase,
  scrollViewportBase,
  scrollContentBase,
  scrollScrollbarBase,
  scrollThumbBase,
  scrollCornerBase,
  cn,
} from '@cloudvoyant/helix';

export type ScrollProps = ScrollAreaRootProps & {
  orientation?: 'vertical' | 'horizontal' | 'both';
  /** `default` shows the styled scrollbars; `hidden` keeps scrolling without rendering any scrollbar. */
  variant?: 'default' | 'hidden';
  contentClassName?: string;
  thumbClassName?: string;
  /** Overrides the viewport class. The default is `flex h-full w-full flex-col`;
   * for horizontal scrolling wrap content in a flex row or override this. */
  viewportClassName?: string;
};

export function Scroll({
  className,
  orientation = 'vertical',
  variant = 'default',
  contentClassName,
  thumbClassName,
  viewportClassName,
  children,
  ...props
}: ScrollProps) {
  return (
    <ArkRoot className={cn(scrollRootBase, className)} {...props}>
      <ArkViewport className={cn(scrollViewportBase, viewportClassName)}>
        <ArkContent className={cn(scrollContentBase, contentClassName)}>{children}</ArkContent>
      </ArkViewport>
      {variant === 'hidden' ? null : (
        <>
          {(orientation === 'vertical' || orientation === 'both') && (
            <ArkScrollbar orientation="vertical" className={scrollScrollbarBase}>
              <ArkThumb className={cn(scrollThumbBase, thumbClassName)} />
            </ArkScrollbar>
          )}
          {(orientation === 'horizontal' || orientation === 'both') && (
            <ArkScrollbar orientation="horizontal" className={scrollScrollbarBase}>
              <ArkThumb className={cn(scrollThumbBase, thumbClassName)} />
            </ArkScrollbar>
          )}
          {orientation === 'both' && <ArkCorner className={scrollCornerBase} />}
        </>
      )}
    </ArkRoot>
  );
}
