// libs/wicn-svelte/src/Center.svelte
<!-- libs/wicn-svelte/src/Center.svelte -->
<!-- Closely based on: Chakra UI Center, built on @ark-ui/svelte/factory (Ark UI), mirrored from wicn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { centerBase, cn } from 'wicn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(centerBase, className));
</script>

<Ark as="div" class={classes} {...rest}>
  {@render children?.()}
</Ark>

// libs/wicn-react/src/center.tsx
// libs/wicn-react/src/center.tsx
// Closely based on: Chakra UI Center, built on @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { centerBase, cn } from 'wicn-core';

export type CenterProps = HTMLArkProps<'div'>;

export function Center({ className, ...props }: CenterProps) {
  return <ark.div className={cn(centerBase, className)} {...props} />;
}
