// libs/vortex-react/src/sidebar/MenuSubButton.tsx
// libs/vortex-react/src/sidebar/MenuSubButton.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';

export function MenuSubButton({
  asChild = false,
  size = 'md',
  isActive = false,
  className,
  ...props
}: HTMLArkProps<'a'> & {
  asChild?: boolean;
  size?: 'sm' | 'md';
  isActive?: boolean;
}) {
  return (
    <ark.a
      data-slot="sidebar-menu-sub-button"
      data-sidebar="menu-sub-button"
      data-size={size}
      data-active={isActive}
      asChild={asChild}
      className={cn(sidebarStyles.menuSubButtonClass, className)}
      {...props}
    />
  );
}

// libs/vortex-svelte/src/sidebar/MenuSubButton.svelte
<!-- libs/vortex-svelte/src/SidebarMenuSubButton.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes, HTMLAnchorAttributes } from 'svelte/elements';

  type Props = {
    asChild?: Snippet<[(props: HTMLAnchorAttributes) => HTMLAttributes<HTMLElement>]>;
    size?: 'sm' | 'md';
    isActive?: boolean;
    class?: string;
    children?: Snippet;
  } & HTMLAnchorAttributes;

  let { asChild, size = 'md', isActive = false, class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="a"
  data-slot="sidebar-menu-sub-button"
  data-sidebar="menu-sub-button"
  data-size={size}
  data-active={isActive}
  {asChild}
  class={cn(sidebarStyles.menuSubButtonClass, className)}
  {...rest}
>
  {@render children?.()}
</Ark>
