// libs/vortex-react/src/sidebar/Separator.tsx
// libs/vortex-react/src/sidebar/Separator.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';

export function Separator({ className, ...props }: HTMLArkProps<'div'>) {
  return (
    <ark.div
      data-slot="sidebar-separator"
      data-sidebar="separator"
      role="separator"
      className={cn(sidebarStyles.separatorClass, className)}
      {...props}
    />
  );
}

// libs/vortex-svelte/src/sidebar/Separator.svelte
<!-- libs/vortex-svelte/src/SidebarSeparator.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vortex-ui';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', ...rest }: Props = $props();
</script>

<Ark
  as="div"
  data-slot="sidebar-separator"
  data-sidebar="separator"
  role="separator"
  class={cn(sidebarStyles.separatorClass, className)}
  {...rest}
/>
