// libs/vertex-svelte/src/sidebar/GroupAction.svelte
<!-- libs/vertex-svelte/src/SidebarGroupAction.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes, HTMLAttributes } from 'svelte/elements';

  type Props = {
    asChild?: Snippet<[(props: HTMLButtonAttributes) => HTMLAttributes<HTMLElement>]>;
    class?: string;
    children?: Snippet;
  } & HTMLButtonAttributes;

  let { asChild, class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="button"
  data-slot="sidebar-group-action"
  data-sidebar="group-action"
  {asChild}
  type="button"
  class={cn(sidebarStyles.groupActionClass, className)}
  {...rest}
>
  {@render children?.()}
</Ark>

// libs/vertex-react/src/sidebar/GroupAction.tsx
// libs/vertex-react/src/sidebar/GroupAction.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';

export function GroupAction({ className, asChild = false, ...props }: HTMLArkProps<'button'> & { asChild?: boolean }) {
  return (
    <ark.button
      data-slot="sidebar-group-action"
      data-sidebar="group-action"
      asChild={asChild}
      type="button"
      className={cn(sidebarStyles.groupActionClass, className)}
      {...props}
    />
  );
}
