// libs/vertex-svelte/src/sidebar/Header.svelte
<!-- libs/vertex-svelte/src/SidebarHeader.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';
  import Col from '../Col.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Col data-slot="sidebar-header" data-sidebar="header" class={cn(sidebarStyles.headerClass, className)} {...rest}>
  {@render children?.()}
</Col>

// libs/vertex-react/src/sidebar/Header.tsx
// libs/vertex-react/src/sidebar/Header.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';
import { Col } from '../col';

export function Header({ className, ...props }: HTMLArkProps<'div'>) {
  return (
    <Col
      data-slot="sidebar-header"
      data-sidebar="header"
      className={cn(sidebarStyles.headerClass, className)}
      {...props}
    />
  );
}
