// libs/vertex-svelte/src/sidebar/Input.svelte
<!-- libs/vertex-svelte/src/SidebarInput.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';
  import type { HTMLInputAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
  } & HTMLInputAttributes;

  let { class: className = '', ...rest }: Props = $props();
</script>

<Ark
  as="input"
  data-slot="sidebar-input"
  data-sidebar="input"
  class={cn(sidebarStyles.inputClass, className)}
  {...rest}
/>

// libs/vertex-react/src/sidebar/Input.tsx
// libs/vertex-react/src/sidebar/Input.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';

export function Input({ className, ...props }: HTMLArkProps<'input'>) {
  return (
    <ark.input
      data-slot="sidebar-input"
      data-sidebar="input"
      className={cn(sidebarStyles.inputClass, className)}
      {...props}
    />
  );
}
