// libs/wicn-react/src/button.tsx
// libs/wicn-react/src/button.tsx
// Closely based on: @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { buttonVariants, cn } from 'wicn-core';
import type { ButtonProps as ButtonPropsBase } from 'wicn-core';

export type ButtonProps = HTMLArkProps<'button'> & ButtonPropsBase;

export function Button({ className, variant, color, size, type = 'button', ...props }: ButtonProps) {
  return <ark.button type={type} className={cn(buttonVariants({ variant, color, size }), className)} {...props} />;
}

// libs/wicn-svelte/src/Button.svelte
<!-- libs/wicn-svelte/src/Button.svelte -->
<!-- Closely based on: @ark-ui/svelte/factory (Ark UI), mirrored from wicn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { buttonVariants, cn } from 'wicn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  type Props = {
    variant?: 'solid' | 'outline' | 'text';
    color?: 'primary' | 'secondary' | 'success' | 'danger' | 'warn' | 'info';
    size?: 'sm' | 'md' | 'lg' | 'icon';
    class?: string;
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
    children?: Snippet;
  } & HTMLButtonAttributes;

  let {
    variant = 'solid',
    color = 'primary',
    size = 'md',
    class: className = '',
    type = 'button',
    disabled = false,
    children,
    ...rest
  }: Props = $props();

  const classes = $derived(cn(buttonVariants({ variant, color, size }), className));
</script>

<Ark as="button" class={classes} {type} {disabled} {...rest}>
  {@render children?.()}
</Ark>
