// libs/wicn-react/src/toggle-button.tsx
// libs/wicn-react/src/toggle-button.tsx
// Closely based on: @ark-ui/react/toggle (Ark UI)
import { ToggleRoot, ToggleIndicator, type ToggleRootProps, type ToggleIndicatorProps } from '@ark-ui/react/toggle';
import { toggleButtonVariants, cn } from 'wicn-core';
import type { ToggleButtonProps as ToggleButtonPropsBase } from 'wicn-core';

export type ToggleButtonProps = ToggleRootProps & ToggleButtonPropsBase;

export function ToggleButton({ className, variant, size, ...props }: ToggleButtonProps) {
  return <ToggleRoot className={cn(toggleButtonVariants({ variant, size }), className)} {...props} />;
}

export function ToggleButtonIndicator(props: ToggleIndicatorProps) {
  return <ToggleIndicator {...props} />;
}

// libs/wicn-svelte/src/ToggleButton.svelte
<!-- libs/wicn-svelte/src/ToggleButton.svelte -->
<!-- Closely based on: @ark-ui/svelte/toggle (Ark UI), mirrored from wicn-react -->
<script lang="ts">
  import { ToggleRoot, type ToggleRootProps } from '@ark-ui/svelte/toggle';
  import { toggleButtonVariants, cn } from 'wicn-core';

  type Props = ToggleRootProps & {
    variant?: 'default' | 'outline';
    size?: 'default' | 'sm' | 'lg';
    class?: string;
  };

  let { variant = 'default', size = 'default', class: className = '', ...rest }: Props = $props();

  const classes = $derived(cn(toggleButtonVariants({ variant, size }), className));
</script>

<ToggleRoot class={classes} {...rest} />
