// libs/vortex-react/src/chart.tsx
// libs/vortex-react/src/chart.tsx
// Closely based on: diffbook Chart (packages/diffbook-ui/src/components/Chart.impl.tsx),
// rebuilt on TanStack Charts: the definition is shared with the Svelte adapter.
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { Chart as TanStackChart } from '@tanstack/charts/react';
import { chartRootBase, buildChartDefinition, cn } from '@cloudvoyant/vortex-ui';
import type { ChartProps as ChartPropsBase } from '@cloudvoyant/vortex-ui';

export type ChartProps = HTMLArkProps<'div'> &
  ChartPropsBase & {
    /** Pre-rendered SVG markup (server/static path). When provided the component renders it
     *  immediately and never mounts the client adapter. */
    svg?: string;
  };

export function Chart({ svg, className, ...props }: ChartProps) {
  const { type, height = 320 } = props;

  if (svg !== undefined) {
    return (
      <ark.div data-chart-state="prerendered" data-chart-type={type} className={cn(chartRootBase, className)}>
        <div className="flex w-full justify-center [&>svg]:max-w-full" dangerouslySetInnerHTML={{ __html: svg }} />
      </ark.div>
    );
  }

  // Client render: build the shared definition and hand it to the TanStack React adapter.
  const definition = buildChartDefinition(props);

  return (
    <ark.div data-chart-state="ready" data-chart-type={type} className={cn(chartRootBase, className)}>
      <TanStackChart definition={definition} height={height} ariaLabel={type === 'pie' ? 'Pie chart' : 'Chart'} />
    </ark.div>
  );
}

// libs/vortex-svelte/src/Chart.svelte
<!-- libs/vortex-svelte/src/Chart.svelte -->
<!-- Closely based on: diffbook Chart, rebuilt on TanStack Charts (shared definition with React),
     mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Chart as TanStackChart } from '@tanstack/charts/svelte';
  import { chartRootBase, cn, buildChartDefinition } from '@cloudvoyant/vortex-ui';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    type: 'line' | 'bar' | 'area' | 'pie';
    data: Record<string, string | number>[];
    series: { key: string; label?: string; color?: string }[];
    xKey?: string;
    nameKey?: string;
    height?: number;
    showLegend?: boolean;
    showGrid?: boolean;
    showAxis?: boolean;
    /** Pre-rendered SVG markup (server/static path). */
    svg?: string;
    class?: string;
  } & HTMLAttributes<HTMLDivElement>;

  let {
    type,
    data,
    series,
    xKey = 'name',
    nameKey = 'name',
    height = 320,
    showLegend = true,
    showGrid = true,
    showAxis = true,
    svg = undefined,
    class: className = '',
    ...rest
  }: Props = $props();

  const definition = $derived(
    buildChartDefinition({ type, data, series, xKey, nameKey, height, showLegend, showGrid, showAxis }),
  );

  const classes = $derived(cn(chartRootBase, className));
</script>

<div data-chart-state={svg !== undefined ? 'prerendered' : 'ready'} data-chart-type={type} class={classes} {...rest}>
  {#if svg !== undefined}
    <div class="flex w-full justify-center [&>svg]:max-w-full">{@html svg}</div>
  {:else}
    <TanStackChart definition={definition} {height} ariaLabel={type === 'pie' ? 'Pie chart' : 'Chart'} />
  {/if}
</div>
