// libs/vortex-react/src/figure.tsx
// libs/vortex-react/src/figure.tsx
// Closely based on: diffbook Figure (packages/diffbook-ui/src/components/Figure.tsx)
import type { ReactNode } from 'react';
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { figureRootBase, figureImageBase, figureCaptionBase, cn } from '@cloudvoyant/vortex-ui';
import type { FigureProps as FigurePropsBase } from '@cloudvoyant/vortex-ui';

export type FigureProps = HTMLArkProps<'figure'> &
  FigurePropsBase & {
    /** A custom image element (e.g. `<img srcSet="…" sizes="…">`). When provided it replaces
     *  the default `<img>` built from `src`/`alt`. */
    img?: ReactNode;
  };

export function Figure({ src, alt, img, caption, className, ...props }: FigureProps) {
  return (
    <ark.figure className={cn(figureRootBase, className)} {...props}>
      {img ?? (src ? <ark.img src={src} alt={alt} loading="lazy" className={figureImageBase} /> : null)}
      {caption ? <ark.figcaption className={figureCaptionBase}>{caption}</ark.figcaption> : null}
    </ark.figure>
  );
}

// libs/vortex-svelte/src/Figure.svelte
<!-- libs/vortex-svelte/src/Figure.svelte -->
<!-- Closely based on: diffbook Figure (packages/diffbook-ui/src/components/Figure.tsx),
     mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { figureRootBase, figureImageBase, figureCaptionBase, cn } from '@cloudvoyant/vortex-ui';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { Snippet } from 'svelte';

  type Props = {
    src?: string;
    alt?: string;
    caption?: string;
    /** A custom image element (e.g. `<img srcSet="…" sizes="…">`). When provided it replaces
     *  the default `<img>` built from `src`/`alt`. */
    img?: Snippet;
    class?: string;
  } & HTMLAttributes<HTMLElement>;

  let { src, alt, img, caption, class: className = '', ...rest }: Props = $props();

  const classes = $derived(cn(figureRootBase, className));
</script>

<Ark as="figure" class={classes} {...rest}>
  {#if img}
    {@render img()}
  {:else if src}
    <Ark as="img" {src} {alt} loading="lazy" class={figureImageBase} />
  {/if}
  {#if caption}<Ark as="figcaption" class={figureCaptionBase}>{caption}</Ark>{/if}
</Ark>
