// libs/vortex-svelte/src/Mermaid.svelte
<!-- libs/vortex-svelte/src/Mermaid.svelte -->
<!-- Closely based on: diffbook Mermaid (packages/diffbook-ui/src/components/Mermaid.tsx placeholder +
     apps/book/src/components/article-body.tsx client renderer), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import {
    mermaidRootBase,
    mermaidSourceBase,
    mermaidSvgBase,
    mermaidLoadingBase,
    renderMermaidSource,
    mermaidSvgAspectRatio,
    cn,
  } from '@cloudvoyant/vortex-ui';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    /** Mermaid diagram source. */
    code: string;
    /** Pre-rendered SVG markup. When provided the component renders it immediately and never
     *  imports `mermaid` client-side — the server-side rendering path. The SVG should carry a
     *  `viewBox` so its aspect ratio can be reserved (no layout shift). */
    svg?: string;
    /** Extra classes for the root container. */
    class?: string;
  } & HTMLAttributes<HTMLDivElement>;

  let { code, svg = undefined, class: className = '', ...rest }: Props = $props();

  type Status = 'loading' | 'done' | 'error';
  let status = $state<Status>(svg !== undefined ? 'done' : 'loading');
  let rendered = $state<string | null>(svg ?? null);

  $effect(() => {
    if (svg !== undefined) return; // prerendered — nothing to load client-side
    let cancelled = false;
    status = 'loading';
    rendered = null;
    renderMermaidSource(code)
      .then((markup) => {
        if (!cancelled) {
          rendered = markup;
          status = 'done';
        }
      })
      .catch(() => {
        if (!cancelled) status = 'error';
      });
    return () => {
      cancelled = true;
    };
  });

  const aspectRatio = $derived(rendered !== null ? mermaidSvgAspectRatio(rendered) : undefined);
  const classes = $derived(cn(mermaidRootBase, className));
  // Svelte style is a string; append aspect-ratio last so the diagram's ratio wins over
  // any caller style and the swap never shifts layout (matches the React wrapper).
  const styles = $derived(
    aspectRatio !== undefined
      ? `${rest.style ? `${rest.style.trim().replace(/;?\s*$/, '')};` : ''}aspect-ratio: ${aspectRatio};`
      : rest.style,
  );
</script>

<Ark
  as="div"
  {...rest}
  data-mermaid-code={JSON.stringify(code)}
  data-mermaid-src={rendered !== null ? code : undefined}
  data-mermaid-state={status}
  style={styles}
  class={classes}
>
  {#if rendered !== null}
    <div class={mermaidSvgBase}>{@html rendered}</div>
  {:else if status === 'error'}
    <pre class={mermaidSourceBase}>{code}</pre>
  {:else}
    <div class={mermaidLoadingBase} role="status" aria-label="Rendering diagram" data-mermaid-loading>
      <span
        aria-hidden="true"
        class="h-5 w-5 shrink-0 animate-spin rounded-full border-2 border-muted-foreground/25 border-t-muted-foreground"></span>
      <span class="text-sm text-muted-foreground">Rendering diagram</span>
    </div>
    <noscript>
      <!-- Only active with JS disabled: hide the loading spinner, which can never resolve,
           and show the raw source instead. -->
      <style>[data-mermaid-loading]{display:none}</style>
      <pre class={mermaidSourceBase}>{code}</pre>
    </noscript>
  {/if}
</Ark>

// libs/vortex-react/src/mermaid.tsx
// libs/vortex-react/src/mermaid.tsx
// Closely based on: diffbook Mermaid (packages/diffbook-ui/src/components/Mermaid.tsx placeholder +
// apps/book/src/components/article-body.tsx client renderer)
import { useEffect, useState } from 'react';
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import {
  mermaidRootBase,
  mermaidSourceBase,
  mermaidSvgBase,
  mermaidLoadingBase,
  renderMermaidSource,
  mermaidSvgAspectRatio,
  cn,
} from '@cloudvoyant/vortex-ui';
import type { MermaidProps as MermaidPropsBase } from '@cloudvoyant/vortex-ui';

export type MermaidProps = HTMLArkProps<'div'> & MermaidPropsBase;

type Status = 'loading' | 'done' | 'error';

/**
 * Mermaid diagram. Two rendering paths:
 *
 * - **Prerendered** (`svg` prop): the SVG markup is rendered immediately — the server/static
 *   path. `mermaid` is never imported client-side. Its `viewBox` reserves the aspect ratio on
 *   the root container, so the diagram paints at its final size with no layout shift.
 * - **Client** (no `svg`): an SSR-safe loading skeleton is shown while `mermaid` is dynamically
 *   imported and the diagram renders; the source stays available in a `<noscript>` block for
 *   no-JS users and is shown directly if the render fails.
 */
export function Mermaid({ code, svg, className, ...props }: MermaidProps) {
  const [status, setStatus] = useState<Status>(svg === undefined ? 'loading' : 'done');
  const [rendered, setRendered] = useState<string | null>(svg ?? null);
  const aspectRatio = rendered === null ? undefined : mermaidSvgAspectRatio(rendered);

  useEffect(() => {
    if (svg !== undefined) return; // prerendered — nothing to load client-side
    let cancelled = false;
    setStatus('loading');
    setRendered(null);
    renderMermaidSource(code)
      .then((markup) => {
        if (!cancelled) {
          setRendered(markup);
          setStatus('done');
        }
      })
      .catch(() => {
        if (!cancelled) setStatus('error');
      });
    return () => {
      cancelled = true;
    };
  }, [code, svg]);

  return (
    <ark.div
      {...props}
      data-mermaid-code={JSON.stringify(code)}
      data-mermaid-src={rendered === null ? undefined : code}
      data-mermaid-state={status}
      // aspectRatio is applied last so the diagram's ratio wins over any caller style and
      // the swap never shifts layout (matches the Svelte wrapper).
      style={aspectRatio === undefined ? props.style : { ...props.style, aspectRatio }}
      className={cn(mermaidRootBase, className)}
    >
      {rendered === null ? (
        status === 'error' ? (
          <pre className={mermaidSourceBase}>{code}</pre>
        ) : (
          <>
            <div className={mermaidLoadingBase} role="status" aria-label="Rendering diagram" data-mermaid-loading>
              <span
                aria-hidden="true"
                className="h-5 w-5 shrink-0 animate-spin rounded-full border-2 border-muted-foreground/25 border-t-muted-foreground"
              />
              <span className="text-sm text-muted-foreground">Rendering diagram</span>
            </div>
            <noscript>
              {/* Only active with JS disabled: hide the loading spinner, which can never
                resolve, and show the raw source instead. */}
              <style>{'[data-mermaid-loading]{display:none}'}</style>
              <pre className={mermaidSourceBase}>{code}</pre>
            </noscript>
          </>
        )
      ) : (
        <div className={mermaidSvgBase} dangerouslySetInnerHTML={{ __html: rendered }} />
      )}
    </ark.div>
  );
}
