// libs/vertex-svelte/src/Input.svelte
<!-- libs/vertex-svelte/src/Input.svelte -->
<!-- Closely based on: Shark UI input (@ark-ui/svelte/field), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { FieldInput, type FieldInputProps } from '@ark-ui/svelte/field';
  import { inputVariants, cn } from '@cloudvoyant/vertex-ui';

  type Props = Omit<FieldInputProps, 'size'> & {
    size?: 'sm' | 'md' | 'lg';
    class?: string;
  };

  let { size = 'md', class: className = '', ...rest }: Props = $props();

  const classes = $derived(cn(inputVariants({ size }), className));
</script>

<FieldInput class={classes} {...rest} />

// libs/vertex-react/src/input.tsx
// libs/vertex-react/src/input.tsx
// Closely based on: Shark UI input (@ark-ui/react/field)
import { FieldInput, type FieldInputProps } from '@ark-ui/react/field';
import { inputVariants, cn } from '@cloudvoyant/vertex-ui';
import type { InputProps as InputBaseProps } from '@cloudvoyant/vertex-ui';

export type InputProps = Omit<FieldInputProps, 'size'> & InputBaseProps;

export function Input({ className, size, ...props }: InputProps) {
  return <FieldInput className={cn(inputVariants({ size }), className)} {...props} />;
}
