// libs/cloudcn-react/src/item.tsx
// libs/cloudcn-react/src/item.tsx
// Source: cloudcn example-item primitive, built on @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { itemBase, cn } from 'cloudcn-core';

export type ItemProps = HTMLArkProps<'div'>;

export function Item({ className, ...props }: ItemProps) {
  return <ark.div className={cn(itemBase, className)} {...props} />;
}

// libs/cloudcn-svelte/src/Item.svelte
<!-- libs/cloudcn-svelte/src/Item.svelte -->
<!-- Source: cloudcn example-item primitive, built on @ark-ui/svelte/factory (Ark UI), mirrored from cloudcn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { itemBase, cn } from 'cloudcn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(itemBase, className));
</script>

<Ark as="div" class={classes} {...rest}>
  {@render children?.()}
</Ark>
