// libs/vortex-react/src/radio-group.tsx
// libs/vortex-react/src/radio-group.tsx
// Closely based on: Shark UI radio group (@ark-ui/react/radio-group)
import {
  RadioGroupRoot,
  RadioGroupItem as ArkRadioGroupItem,
  RadioGroupItemControl,
  RadioGroupItemText,
  RadioGroupItemHiddenInput,
  useRadioGroupContext,
  useRadioGroupItemContext,
  type RadioGroupRootProps,
  type RadioGroupItemProps as ArkRadioGroupItemProps,
} from '@ark-ui/react/radio-group';
import { radioGroupRootBase, radioGroupItemControlBase, radioGroupItemTextBase, cn } from '@cloudvoyant/vortex-ui';

export type RadioGroupProps = RadioGroupRootProps;

export function RadioGroup({ className, ...props }: RadioGroupProps) {
  return <RadioGroupRoot className={cn(radioGroupRootBase, className)} {...props} />;
}

export type RadioGroupItemProps = ArkRadioGroupItemProps;

export function RadioGroupItem({ className, children, ...props }: RadioGroupItemProps) {
  return (
    <ArkRadioGroupItem className={cn('flex cursor-pointer items-center gap-2.5', className)} {...props}>
      <RadioGroupItemControl className={radioGroupItemControlBase}>
        <span className="size-1.5 rounded-full bg-current hidden [[data-state=checked]>&]:block" />
      </RadioGroupItemControl>
      <RadioGroupItemText className={radioGroupItemTextBase}>{children}</RadioGroupItemText>
      <RadioGroupItemHiddenInput />
    </ArkRadioGroupItem>
  );
}

export const useRadioGroup = useRadioGroupContext;
export const useRadioGroupItem = useRadioGroupItemContext;

// libs/vortex-svelte/src/radio-group/RadioGroup.svelte
<!-- libs/vortex-svelte/src/radio-group/RadioGroup.svelte -->
<!-- Closely based on: Shark UI radio group (@ark-ui/svelte/radio-group), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { RadioGroupRoot, type RadioGroupRootProps } from '@ark-ui/svelte/radio-group';
  import { radioGroupRootBase, cn } from '@cloudvoyant/vortex-ui';

  type Props = RadioGroupRootProps & { class?: string };

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(radioGroupRootBase, className));
</script>

<RadioGroupRoot class={classes} {...rest}>
  {@render children?.()}
</RadioGroupRoot>
