// libs/wicn-svelte/src/sidebar/MenuItem.svelte
<!-- libs/wicn-svelte/src/SidebarMenuItem.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from wicn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from 'wicn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLLIElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="li"
  data-slot="sidebar-menu-item"
  data-sidebar="menu-item"
  class={cn(sidebarStyles.menuItemClass, className)}
  {...rest}
>
  {@render children?.()}
</Ark>

// libs/wicn-react/src/sidebar/MenuItem.tsx
// libs/wicn-react/src/sidebar/MenuItem.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from 'wicn-core';

export function MenuItem({ className, ...props }: HTMLArkProps<'li'>) {
  return (
    <ark.li
      data-slot="sidebar-menu-item"
      data-sidebar="menu-item"
      className={cn(sidebarStyles.menuItemClass, className)}
      {...props}
    />
  );
}
