// libs/helix-react/src/badge.tsx
// libs/helix-react/src/badge.tsx
// Closely based on: @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { badgeVariants, cn } from '@cloudvoyant/helix';
import type { BadgeProps as BadgePropsBase } from '@cloudvoyant/helix';

export type BadgeProps = HTMLArkProps<'span'> & BadgePropsBase;

export function Badge({ className, variant, color, size, ...props }: BadgeProps) {
  return <ark.span className={cn(badgeVariants({ variant, color, size }), className)} {...props} />;
}

// libs/helix-svelte/src/Badge.svelte
<!-- libs/helix-svelte/src/Badge.svelte -->
<!-- Closely based on: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { badgeVariants, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    variant?: 'solid' | 'subtle' | 'outline' | 'surface' | 'plain';
    color?: 'primary' | 'secondary' | 'success' | 'danger' | 'warn' | 'info';
    size?: 'xs' | 'sm' | 'md' | 'lg';
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLSpanElement>;

  let { variant = 'subtle', color = 'primary', size = 'sm', class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(badgeVariants({ variant, color, size }), className));
</script>

<Ark as="span" class={classes} {...rest}>
  {@render children?.()}
</Ark>
