// libs/helix-react/src/container.tsx
// libs/helix-react/src/container.tsx
// Closely based on: Chakra UI Container, built on @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { containerBase, cn } from '@cloudvoyant/helix';

export type ContainerProps = HTMLArkProps<'div'>;

export function Container({ className, ...props }: ContainerProps) {
  return <ark.div className={cn(containerBase, className)} {...props} />;
}

// libs/helix-svelte/src/Container.svelte
<!-- libs/helix-svelte/src/Container.svelte -->
<!-- Closely based on: Chakra UI Container, built on @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { containerBase, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(containerBase, className));
</script>

<Ark as="div" class={classes} {...rest}>
  {@render children?.()}
</Ark>
