// libs/helix-react/src/prevnext.tsx
// libs/helix-react/src/prevnext.tsx
// Closely based on: diffbook PrevNext (packages/diffbook-ui/src/components/PrevNext.tsx)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import {
  prevNextRootBase,
  prevNextLinkBase,
  prevNextLinkNextBase,
  prevNextDirectionBase,
  prevNextTitleBase,
  prevNextSpacerBase,
  cn,
} from '@cloudvoyant/helix';
import type { PrevNextProps as PrevNextPropsBase } from '@cloudvoyant/helix';

export type PrevNextProps = HTMLArkProps<'nav'> & PrevNextPropsBase;

export function PrevNext({ prev, next, className, ...props }: PrevNextProps) {
  if (!prev && !next) return null;
  return (
    <ark.nav className={cn(prevNextRootBase, className)} aria-label="Previous and next pages" {...props}>
      {prev ? (
        <ark.a href={prev.href} className={prevNextLinkBase}>
          <ark.span className={prevNextDirectionBase}>Previous</ark.span>
          <ark.span className={prevNextTitleBase}>← {prev.title}</ark.span>
        </ark.a>
      ) : (
        <ark.span className={prevNextSpacerBase} />
      )}
      {next ? (
        <ark.a href={next.href} className={cn(prevNextLinkBase, prevNextLinkNextBase)}>
          <ark.span className={prevNextDirectionBase}>Next</ark.span>
          <ark.span className={prevNextTitleBase}>{next.title} →</ark.span>
        </ark.a>
      ) : (
        <ark.span className={prevNextSpacerBase} />
      )}
    </ark.nav>
  );
}

// libs/helix-svelte/src/PrevNext.svelte
<!-- libs/helix-svelte/src/PrevNext.svelte -->
<!-- Closely based on: diffbook PrevNext (packages/diffbook-ui/src/components/PrevNext.tsx),
     mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import {
    prevNextRootBase,
    prevNextLinkBase,
    prevNextLinkNextBase,
    prevNextDirectionBase,
    prevNextTitleBase,
    prevNextSpacerBase,
    cn,
  } from '@cloudvoyant/helix';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    prev?: { title: string; href: string };
    next?: { title: string; href: string };
    class?: string;
  } & HTMLAttributes<HTMLElement>;

  let { prev, next, class: className = '', ...rest }: Props = $props();

  const classes = $derived(cn(prevNextRootBase, className));
</script>

{#if prev || next}
  <Ark as="nav" class={classes} aria-label="Previous and next pages" {...rest}>
    {#if prev}
      <Ark as="a" href={prev.href} class={prevNextLinkBase}>
        <Ark as="span" class={prevNextDirectionBase}>Previous</Ark>
        <Ark as="span" class={prevNextTitleBase}>← {prev.title}</Ark>
      </Ark>
    {:else}
      <Ark as="span" class={prevNextSpacerBase}></Ark>
    {/if}
    {#if next}
      <Ark as="a" href={next.href} class={cn(prevNextLinkBase, prevNextLinkNextBase)}>
        <Ark as="span" class={prevNextDirectionBase}>Next</Ark>
        <Ark as="span" class={prevNextTitleBase}>{next.title} →</Ark>
      </Ark>
    {:else}
      <Ark as="span" class={prevNextSpacerBase}></Ark>
    {/if}
  </Ark>
{/if}
