// libs/helix-react/src/stack.tsx
// libs/helix-react/src/stack.tsx
// Closely based on: Chakra UI Stack/HStack/VStack, built on @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { stackBase, hstackBase, vstackBase, cn } from '@cloudvoyant/helix';

export type StackProps = HTMLArkProps<'div'>;
export type HStackProps = HTMLArkProps<'div'>;
export type VStackProps = HTMLArkProps<'div'>;

export function Stack({ className, ...props }: StackProps) {
  return <ark.div className={cn(stackBase, className)} {...props} />;
}

export function HStack({ className, ...props }: HStackProps) {
  return <ark.div className={cn(hstackBase, className)} {...props} />;
}

export function VStack({ className, ...props }: VStackProps) {
  return <ark.div className={cn(vstackBase, className)} {...props} />;
}

// libs/helix-svelte/src/Stack.svelte
<!-- libs/helix-svelte/src/Stack.svelte -->
<!-- Closely based on: Chakra UI Stack, built on @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { stackBase, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(stackBase, className));
</script>

<Ark as="div" class={classes} {...rest}>
  {#if children}{@render children()}{/if}
</Ark>
