// libs/helix-react/src/youtube.tsx
// libs/helix-react/src/youtube.tsx
// Closely based on: diffbook YouTube (packages/diffbook-ui/src/components/YouTube.impl.tsx),
// as a dependency-free facade. Accepts a URL; timestamps are composed via YoutubeTimestamps +
// YoutubeTimestampAt (auto-inferred from web metadata, or overridden manually).
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import {
  youtubeRootBase,
  youtubeTitleBase,
  youtubeFacadeBase,
  youtubePlayButtonBase,
  youtubePlayButtonInnerBase,
  youtubeDescriptionBase,
  youtubeChaptersBase,
  youtubeChaptersSummaryBase,
  youtubeChaptersChevronBase,
  youtubeChaptersListBase,
  youtubeChapterButtonBase,
  youtubeChapterTimeBase,
  youtubeChapterLabelBase,
  extractYouTubeId,
  formatTime,
  parseYouTubeChapters,
  fetchYouTubeMetadata,
  cn,
} from '@cloudvoyant/helix';
import type { YouTubeProps as YouTubePropsBase, YouTubeChapter } from '@cloudvoyant/helix';

function PlayIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      className="h-8 w-8"
      aria-hidden="true"
    >
      <path d="M8 5v14l11-7z" />
    </svg>
  );
}

function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className={className}
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

/* ------------------------------------------------------------------ */
/*  Context — lets composed timestamps seek the parent player           */
/* ------------------------------------------------------------------ */

interface YouTubeContextValue {
  url: string;
  videoId: string;
  seek: (t: number) => void;
}

const YouTubeContext = createContext<YouTubeContextValue | null>(null);

function useYouTube(): YouTubeContextValue {
  const ctx = useContext(YouTubeContext);
  if (!ctx) throw new Error('YoutubeTimestamps must be rendered inside a <YouTube>.');
  return ctx;
}

export type YouTubeProps = HTMLArkProps<'div'> & YouTubePropsBase & { children?: ReactNode };

export function YouTube({ url, title, description, poster, className, children, ...props }: YouTubeProps) {
  const videoId = extractYouTubeId(url);
  const posterUrl = poster ?? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
  const [playing, setPlaying] = useState(false);
  const [startAt, setStartAt] = useState<number | null>(null);

  const seek = (t: number) => {
    setStartAt(t);
    setPlaying(true);
  };

  const src = `https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1${startAt != null ? `&start=${startAt}` : ''}`;

  return (
    <YouTubeContext.Provider value={{ url, videoId, seek }}>
      <ark.div data-youtube-id={videoId} className={cn(youtubeRootBase, className)} {...props}>
        {title ? <ark.h3 className={youtubeTitleBase}>{title}</ark.h3> : null}
        {playing ? (
          <iframe
            src={src}
            title={title ?? `YouTube video ${videoId}`}
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            className="aspect-video w-full rounded-md border border-border"
          />
        ) : (
          <ark.button
            type="button"
            className={youtubeFacadeBase}
            onClick={() => setPlaying(true)}
            aria-label={title ? `Play video: ${title}` : 'Play video'}
          >
            <ark.img src={posterUrl} alt={title ?? `YouTube video ${videoId}`} loading="lazy" className="h-full w-full object-cover" />
            <ark.span className={youtubePlayButtonBase} aria-hidden="true">
              <ark.span className={youtubePlayButtonInnerBase}>
                <PlayIcon />
              </ark.span>
            </ark.span>
          </ark.button>
        )}
        {description ? <ark.p className={youtubeDescriptionBase}>{description}</ark.p> : null}
        {children}
      </ark.div>
    </YouTubeContext.Provider>
  );
}

/* ------------------------------------------------------------------ */
/*  Timestamps — auto-inferred from web metadata, or manual overrides   */
/* ------------------------------------------------------------------ */

export type YoutubeTimestampAtProps = HTMLArkProps<'li'> & { t: number; children?: ReactNode };

export function YoutubeTimestampAt({ t, children, className, ...props }: YoutubeTimestampAtProps) {
  const { seek } = useYouTube();
  return (
    <ark.li className={className} {...props}>
      <ark.button type="button" onClick={() => seek(t)} className={youtubeChapterButtonBase}>
        <ark.span className={youtubeChapterTimeBase}>{formatTime(t)}</ark.span>
        <ark.span className={youtubeChapterLabelBase}>{children}</ark.span>
      </ark.button>
    </ark.li>
  );
}

export type YoutubeTimestampsProps = HTMLArkProps<'div'> & {
  /** Manual chapters; when omitted, chapters are auto-inferred from the video's web metadata. */
  chapters?: YouTubeChapter[];
  children?: ReactNode;
};

export function YoutubeTimestamps({ chapters, children, className, ...props }: YoutubeTimestampsProps) {
  const { url } = useYouTube();
  const [inferred, setInferred] = useState<YouTubeChapter[]>([]);
  const [loading, setLoading] = useState(chapters === undefined);

  useEffect(() => {
    if (chapters !== undefined) return;
    let cancelled = false;
    setLoading(true);
    fetchYouTubeMetadata(url)
      .then((meta) => {
        if (!cancelled) {
          setInferred(meta.description ? parseYouTubeChapters(meta.description) : []);
          setLoading(false);
        }
      })
      .catch(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [url, chapters]);

  const resolved = chapters ?? inferred;
  const hasChildren = children !== undefined && children !== null;

  if (!loading && resolved.length === 0 && !hasChildren) return null;

  return (
    <ark.div className={cn(youtubeChaptersBase, className)} {...props}>
      <details className="group" open>
        <ark.summary className={youtubeChaptersSummaryBase}>
          <ChevronRightIcon className={youtubeChaptersChevronBase} />
          <span>Timestamps</span>
        </ark.summary>
        <ark.nav aria-label="Video timestamps" className={youtubeChaptersListBase}>
          <ark.ul className="space-y-1">
            {resolved.map((ch) => (
              <YoutubeTimestampAt key={ch.t} t={ch.t}>
                {ch.label}
              </YoutubeTimestampAt>
            ))}
            {children}
          </ark.ul>
        </ark.nav>
      </details>
    </ark.div>
  );
}

// libs/helix-svelte/src/YouTube.svelte
<!-- libs/helix-svelte/src/YouTube.svelte -->
<!-- Closely based on: diffbook YouTube, mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { getContext, setContext } from 'svelte';
  import {
    youtubeRootBase,
    youtubeTitleBase,
    youtubeFacadeBase,
    youtubePlayButtonBase,
    youtubePlayButtonInnerBase,
    youtubeDescriptionBase,
    youtubeChaptersBase,
    youtubeChaptersSummaryBase,
    youtubeChaptersChevronBase,
    youtubeChaptersListBase,
    youtubeChapterButtonBase,
    youtubeChapterTimeBase,
    youtubeChapterLabelBase,
    extractYouTubeId,
    formatTime,
    parseYouTubeChapters,
    fetchYouTubeMetadata,
    cn,
  } from '@cloudvoyant/helix';
  import type { YouTubeChapter } from '@cloudvoyant/helix';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { Snippet } from 'svelte';

  type Props = {
    url: string;
    title?: string;
    description?: string;
    poster?: string;
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { url, title, description, poster, class: className = '', children, ...rest }: Props = $props();

  const videoId = $derived(extractYouTubeId(url));
  const posterUrl = $derived(poster ?? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`);

  let playing = $state(false);
  let startAt = $state<number | null>(null);

  const seek = (t: number) => {
    startAt = t;
    playing = true;
  };

  setContext('helix-youtube', { url, videoId, seek });

  const src = $derived(
    `https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1${startAt != null ? `&start=${startAt}` : ''}`,
  );

  const classes = $derived(cn(youtubeRootBase, className));
</script>

<Ark as="div" data-youtube-id={videoId} class={classes} {...rest}>
  {#if title}<Ark as="h3" class={youtubeTitleBase}>{title}</Ark>{/if}
  {#if playing}
    <iframe
      {src}
      title={title ?? `YouTube video ${videoId}`}
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
      class="aspect-video w-full rounded-md border border-border"
    ></iframe>
  {:else}
    <Ark as="button" type="button" class={youtubeFacadeBase} onclick={() => (playing = true)} aria-label={title ? `Play video: ${title}` : 'Play video'}>
      <Ark as="img" src={posterUrl} alt={title ?? `YouTube video ${videoId}`} loading="lazy" class="h-full w-full object-cover" />
      <Ark as="span" class={youtubePlayButtonBase} aria-hidden="true">
        <Ark as="span" class={youtubePlayButtonInnerBase}>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-8 w-8" aria-hidden="true">
            <path d="M8 5v14l11-7z"></path>
          </svg>
        </Ark>
      </Ark>
    </Ark>
  {/if}
  {#if description}<Ark as="p" class={youtubeDescriptionBase}>{description}</Ark>{/if}
  {#if children}{@render children()}{/if}
</Ark>
