// libs/vertex-react/src/row.tsx
// libs/vertex-react/src/row.tsx
// Closely based on: Chakra UI Flex (direction="row"), built on @ark-ui/react/factory (Ark UI)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { rowBase, cn } from '@cloudvoyant/vertex-ui';

export type RowProps = HTMLArkProps<'div'>;

export function Row({ className, ...props }: RowProps) {
  return <ark.div className={cn(rowBase, className)} {...props} />;
}

// libs/vertex-svelte/src/Row.svelte
<!-- libs/vertex-svelte/src/Row.svelte -->
<!-- Closely based on: Chakra UI Flex (direction="row"), built on @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { rowBase, cn } from '@cloudvoyant/vertex-ui';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { class: className = '', children, ...rest }: Props = $props();

  const classes = $derived(cn(rowBase, className));
</script>

<Ark as="div" class={classes} {...rest}>
  {@render children?.()}
</Ark>
