// libs/helix-svelte/src/sidebar/MenuSub.svelte
<!-- libs/helix-svelte/src/SidebarMenuSub.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLUListElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="ul"
  data-slot="sidebar-menu-sub"
  data-sidebar="menu-sub"
  class={cn(sidebarStyles.menuSubClass, className)}
  {...rest}
>
  {#if children}{@render children()}{/if}
</Ark>

// libs/helix-react/src/sidebar/MenuSub.tsx
// libs/helix-react/src/sidebar/MenuSub.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/helix';

export function MenuSub({ className, ...props }: HTMLArkProps<'ul'>) {
  return (
    <ark.ul
      data-slot="sidebar-menu-sub"
      data-sidebar="menu-sub"
      className={cn(sidebarStyles.menuSubClass, className)}
      {...props}
    />
  );
}
