// libs/helix-svelte/src/sidebar/MenuSubItem.svelte
<!-- libs/helix-svelte/src/SidebarMenuSubItem.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/helix';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLLIElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark
  as="li"
  data-slot="sidebar-menu-sub-item"
  data-sidebar="menu-sub-item"
  class={cn(sidebarStyles.menuSubItemClass, className)}
  {...rest}
>
  {#if children}{@render children()}{/if}
</Ark>

// libs/helix-react/src/sidebar/MenuSubItem.tsx
// libs/helix-react/src/sidebar/MenuSubItem.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/helix';

export function MenuSubItem({ className, ...props }: HTMLArkProps<'li'>) {
  return (
    <ark.li
      data-slot="sidebar-menu-sub-item"
      data-sidebar="menu-sub-item"
      className={cn(sidebarStyles.menuSubItemClass, className)}
      {...props}
    />
  );
}
