// libs/helix-svelte/src/sidebar/Root.svelte
<!-- libs/helix-svelte/src/Sidebar.svelte -->
<!-- Source: @ark-ui/svelte/drawer (Ark UI), mirrored from @cloudvoyant/helix-react -->
<script lang="ts">
  import {
    DrawerRoot,
    DrawerBackdrop,
    DrawerPositioner,
    DrawerContent,
    DrawerTitle,
    DrawerDescription,
    DrawerCloseTrigger,
  } from '@ark-ui/svelte/drawer';
  import { SIDEBAR_WIDTH_MOBILE, sidebarStyles, cn } from '@cloudvoyant/helix';
  import Col from '../Col.svelte';
  import { getSidebarContext } from './context.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    side?: 'left' | 'right';
    variant?: 'sidebar' | 'floating' | 'inset';
    collapsible?: 'offcanvas' | 'icon' | 'none';
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement> & { id?: string; role?: 'dialog' | 'alertdialog' };

  let {
    side = 'left',
    variant = 'sidebar',
    collapsible = 'offcanvas',
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  const sidebar = getSidebarContext();
  const state = $derived(sidebar.state);
  const isMobile = $derived(sidebar.isMobile);
  const openMobile = $derived(sidebar.openMobile);
  const setOpenMobile = sidebar.setOpenMobile;

  const containerClasses = $derived(
    cn(
      sidebarStyles.containerClass,
      side === 'left'
        ? 'left-0 group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)]'
        : 'right-0 group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)]',
      variant === 'floating' || variant === 'inset'
        ? 'p-2 group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4))+2px)]'
        : 'group-data-[collapsible=icon]:w-(--sidebar-width-icon) group-data-[side=left]:border-r group-data-[side=right]:border-l',
      className,
    ),
  );

  const gapClasses = $derived(
    cn(
      sidebarStyles.gapClass,
      side === 'right' && 'rotate-180',
      variant === 'floating' || variant === 'inset'
        ? 'group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4)))]'
        : 'group-data-[collapsible=icon]:w-(--sidebar-width-icon)',
    ),
  );
</script>

{#if collapsible === 'none'}
  <Col
    data-slot="sidebar"
    data-sidebar="sidebar"
    class={cn('h-full w-(--sidebar-width) bg-sidebar text-sidebar-foreground', className)}
    {...rest}
  >
    {@render children?.()}
  </Col>
{:else if isMobile}
  <DrawerRoot
    open={openMobile}
    onOpenChange={(details) => setOpenMobile(details.open)}
    swipeDirection={side === 'left' ? 'start' : 'down'}
    {...rest}
  >
    <DrawerBackdrop class={sidebarStyles.mobileBackdropClass} />
    <DrawerPositioner class={sidebarStyles.mobilePositionerClass}>
      <DrawerContent
        data-sidebar="sidebar"
        data-slot="sidebar"
        data-mobile="true"
        class={cn(sidebarStyles.mobileContentClass, className)}
        style={`--sidebar-width: ${SIDEBAR_WIDTH_MOBILE};`}
      >
        <DrawerTitle class="sr-only">Sidebar</DrawerTitle>
        <DrawerDescription class="sr-only">Displays the mobile sidebar.</DrawerDescription>
        <DrawerCloseTrigger class="hidden" />
        <Col class="h-full w-full">{@render children?.()}</Col>
      </DrawerContent>
    </DrawerPositioner>
  </DrawerRoot>
{:else}
  <div
    class="group peer hidden text-sidebar-foreground md:block"
    data-state={state}
    data-collapsible={state === 'collapsed' ? collapsible : ''}
    data-variant={variant}
    data-side={side}
    data-slot="sidebar"
  >
    <div data-slot="sidebar-gap" class={gapClasses}></div>
    <div data-slot="sidebar-container" class={containerClasses} {...rest}>
      <Col data-sidebar="sidebar" data-slot="sidebar-inner" data-variant={variant} class={cn(sidebarStyles.innerClass)}>
        {@render children?.()}
      </Col>
    </div>
  </div>
{/if}

// libs/helix-react/src/sidebar/Root.tsx
// libs/helix-react/src/sidebar/Root.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
/// <reference lib="dom" />
import * as React from 'react';
import {
  DrawerRoot,
  DrawerBackdrop,
  DrawerPositioner,
  DrawerContent,
  DrawerTitle,
  DrawerDescription,
  DrawerCloseTrigger,
  type DrawerRootProps,
} from '@ark-ui/react/drawer';
import { SIDEBAR_WIDTH_MOBILE, sidebarStyles, cn } from '@cloudvoyant/helix';
import { Col } from '../col';
import { useSidebar } from './context';

export function Root({
  side = 'left',
  variant = 'sidebar',
  collapsible = 'offcanvas',
  className,
  children,
  ...props
}: React.ComponentProps<'div'> & {
  side?: 'left' | 'right';
  variant?: 'sidebar' | 'floating' | 'inset';
  collapsible?: 'offcanvas' | 'icon' | 'none';
}) {
  const { isMobile, state, openMobile, setOpenMobile } = useSidebar();

  if (collapsible === 'none') {
    return (
      <Col
        data-slot="sidebar"
        data-sidebar="sidebar"
        className={cn('h-full w-(--sidebar-width) bg-sidebar text-sidebar-foreground', className)}
        {...props}
      >
        {children}
      </Col>
    );
  }

  if (isMobile) {
    return (
      <DrawerRoot
        open={openMobile}
        onOpenChange={(details) => setOpenMobile(details.open)}
        swipeDirection={side === 'left' ? 'start' : 'down'}
        {...(props as DrawerRootProps)}
      >
        <DrawerBackdrop className={sidebarStyles.mobileBackdropClass} />
        <DrawerPositioner className={sidebarStyles.mobilePositionerClass}>
          <DrawerContent
            data-sidebar="sidebar"
            data-slot="sidebar"
            data-mobile="true"
            className={cn(sidebarStyles.mobileContentClass, className)}
            style={{ '--sidebar-width': SIDEBAR_WIDTH_MOBILE } as React.CSSProperties}
          >
            <DrawerTitle className="sr-only">Sidebar</DrawerTitle>
            <DrawerDescription className="sr-only">Displays the mobile sidebar.</DrawerDescription>
            <DrawerCloseTrigger className="hidden" />
            <Col className="h-full w-full">{children}</Col>
          </DrawerContent>
        </DrawerPositioner>
      </DrawerRoot>
    );
  }

  return (
    <div
      className="group peer hidden text-sidebar-foreground md:block"
      data-state={state}
      data-collapsible={state === 'collapsed' ? collapsible : ''}
      data-variant={variant}
      data-side={side}
      data-slot="sidebar"
    >
      <div
        data-slot="sidebar-gap"
        className={cn(
          sidebarStyles.gapClass,
          side === 'right' && 'rotate-180',
          variant === 'floating' || variant === 'inset'
            ? 'group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4)))]'
            : 'group-data-[collapsible=icon]:w-(--sidebar-width-icon)',
        )}
      />
      <div
        data-slot="sidebar-container"
        className={cn(
          sidebarStyles.containerClass,
          side === 'left'
            ? 'left-0 group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)]'
            : 'right-0 group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)]',
          variant === 'floating' || variant === 'inset'
            ? 'p-2 group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4))+2px)]'
            : 'group-data-[collapsible=icon]:w-(--sidebar-width-icon) group-data-[side=left]:border-r group-data-[side=right]:border-l',
          className,
        )}
        {...props}
      >
        <div
          data-sidebar="sidebar"
          data-slot="sidebar-inner"
          data-variant={variant}
          className={cn(sidebarStyles.innerClass)}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
