// libs/vertex-react/src/sidebar/MenuSkeleton.tsx
// libs/vertex-react/src/sidebar/MenuSkeleton.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
/// <reference lib="dom" />
import * as React from 'react';
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';

export function MenuSkeleton({ className, showIcon = false, ...props }: HTMLArkProps<'div'> & { showIcon?: boolean }) {
  const width = React.useMemo(() => `${Math.floor(Math.random() * 40) + 50}%`, []);

  return (
    <ark.div
      data-slot="sidebar-menu-skeleton"
      data-sidebar="menu-skeleton"
      className={cn(sidebarStyles.menuSkeletonClass, className)}
      {...props}
    >
      {showIcon && (
        <ark.div
          className="size-4 shrink-0 animate-pulse rounded-md bg-sidebar-accent"
          data-sidebar="menu-skeleton-icon"
        />
      )}
      <ark.div
        className="h-4 max-w-(--skeleton-width) flex-1 animate-pulse rounded-md bg-sidebar-accent"
        data-sidebar="menu-skeleton-text"
        style={{ '--skeleton-width': width } as React.CSSProperties}
      />
    </ark.div>
  );
}

// libs/vertex-svelte/src/sidebar/MenuSkeleton.svelte
<!-- libs/vertex-svelte/src/SidebarMenuSkeleton.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from @cloudvoyant/vertex-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from '@cloudvoyant/vertex-ui';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    showIcon?: boolean;
    class?: string;
  } & HTMLAttributes<HTMLDivElement>;

  let { showIcon = false, class: className = '', ...rest }: Props = $props();

  const width = $derived(`${Math.floor(Math.random() * 40) + 50}%`);
</script>

<Ark
  as="div"
  data-slot="sidebar-menu-skeleton"
  data-sidebar="menu-skeleton"
  class={cn(sidebarStyles.menuSkeletonClass, className)}
  {...rest}
>
  {#if showIcon}
    <Ark
      as="div"
      class="size-4 shrink-0 animate-pulse rounded-md bg-sidebar-accent"
      data-sidebar="menu-skeleton-icon"
    />
  {/if}
  <Ark
    as="div"
    class="h-4 max-w-(--skeleton-width) flex-1 animate-pulse rounded-md bg-sidebar-accent"
    data-sidebar="menu-skeleton-text"
    style={`--skeleton-width: ${width};`}
  />
</Ark>
