// libs/cloudcn-react/src/sidebar/Group.tsx
// libs/cloudcn-react/src/sidebar/Group.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from 'cloudcn-core';
import { Col } from '../col';

export function Group({ label, className, children, ...props }: HTMLArkProps<'div'> & { label?: string }) {
  return (
    <Col data-slot="sidebar-group" data-sidebar="group" className={cn(sidebarStyles.groupClass, className)} {...props}>
      {label && (
        <div data-slot="sidebar-group-label" data-sidebar="group-label" className={cn(sidebarStyles.groupLabelClass)}>
          {label}
        </div>
      )}
      <div data-slot="sidebar-group-content" data-sidebar="group-content" className={cn(sidebarStyles.groupContentClass)}>
        {children}
      </div>
    </Col>
  );
}

// libs/cloudcn-svelte/src/sidebar/Group.svelte
<!-- libs/cloudcn-svelte/src/sidebar/Group.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from cloudcn-react -->
<script lang="ts">
  import { sidebarStyles, cn } from 'cloudcn-core';
  import Col from '../Col.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    label?: string;
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { label, class: className = '', children, ...rest }: Props = $props();
</script>

<Col data-slot="sidebar-group" data-sidebar="group" class={cn(sidebarStyles.groupClass, className)} {...rest}>
  {#if label}
    <div data-slot="sidebar-group-label" data-sidebar="group-label" class={cn(sidebarStyles.groupLabelClass)}>
      {label}
    </div>
  {/if}
  <div data-slot="sidebar-group-content" data-sidebar="group-content" class={cn(sidebarStyles.groupContentClass)}>
    {@render children?.()}
  </div>
</Col>
