// libs/cloudcn-react/src/sidebar/Inset.tsx
// libs/cloudcn-react/src/sidebar/Inset.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from 'cloudcn-core';

export function Inset({ className, ...props }: HTMLArkProps<'main'>) {
  return <ark.main data-slot="sidebar-inset" className={cn(sidebarStyles.insetClass, className)} {...props} />;
}

// libs/cloudcn-svelte/src/sidebar/Inset.svelte
<!-- libs/cloudcn-svelte/src/sidebar/Inset.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from cloudcn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from 'cloudcn-core';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLElement>;

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<Ark as="main" data-slot="sidebar-inset" class={cn(sidebarStyles.insetClass, className)} {...rest}>
  {@render children?.()}
</Ark>
