// libs/cloudcn-react/src/sidebar/Trigger.tsx
// libs/cloudcn-react/src/sidebar/Trigger.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { sidebarStyles, cn } from 'cloudcn-core';
import { useSidebar } from './context';

export function Trigger({ className, onClick, children, ...props }: HTMLArkProps<'button'>) {
  const { toggleSidebar } = useSidebar();

  return (
    <ark.button
      data-sidebar="trigger"
      data-slot="sidebar-trigger"
      type="button"
      aria-label="Toggle Sidebar"
      className={cn(sidebarStyles.triggerClass, className)}
      onClick={(event) => {
        onClick?.(event);
        toggleSidebar();
      }}
      {...props}
    >
      {children}
    </ark.button>
  );
}

// libs/cloudcn-svelte/src/sidebar/Trigger.svelte
<!-- libs/cloudcn-svelte/src/SidebarTrigger.svelte -->
<!-- Source: @ark-ui/svelte/factory (Ark UI), mirrored from cloudcn-react -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { sidebarStyles, cn } from 'cloudcn-core';
  import { getSidebarContext } from './context.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  type Props = {
    class?: string;
    children?: Snippet;
  } & HTMLButtonAttributes;

  let { class: className = '', children, onclick, ...rest }: Props = $props();

  const { toggleSidebar } = getSidebarContext();
</script>

<Ark
  as="button"
  data-sidebar="trigger"
  data-slot="sidebar-trigger"
  type="button"
  aria-label="Toggle Sidebar"
  class={cn(sidebarStyles.triggerClass, className)}
  onclick={(e) => {
    onclick?.(e);
    toggleSidebar();
  }}
  {...rest}
>
  {@render children?.()}
</Ark>
