// libs/vortex-react/src/tabs.tsx
// libs/vortex-react/src/tabs.tsx
// Closely based on: Shark UI tabs (https://shark.vini.one/docs/components/tabs, @ark-ui/react/tabs)
import {
  TabsRoot,
  TabList,
  TabIndicator,
  TabTrigger,
  TabContent,
  useTabsContext,
  type TabsRootProps,
  type TabListProps,
  type TabTriggerProps,
  type TabContentProps,
} from '@ark-ui/react/tabs';
import {
  tabsRootBase,
  tabsListBase,
  tabsListVariants,
  tabsIndicatorBase,
  tabsIndicatorVariants,
  tabsTriggerBase,
  tabsContentBase,
  cn,
  type TabsListVariants,
} from '@cloudvoyant/vortex-ui';

export type TabsProps = TabsRootProps;

export function Tabs({ className, lazyMount = true, unmountOnExit = true, ...props }: TabsProps) {
  return (
    <TabsRoot lazyMount={lazyMount} unmountOnExit={unmountOnExit} className={cn(tabsRootBase, className)} {...props} />
  );
}

export type TabsListProps = TabListProps & TabsListVariants;

export function TabsList({ variant = 'default', className, children, ...props }: TabsListProps) {
  return (
    <TabList className={cn(tabsListBase, tabsListVariants({ variant }), className)} {...props}>
      {children}
      <TabIndicator className={cn(tabsIndicatorBase, tabsIndicatorVariants({ variant }))} />
    </TabList>
  );
}

export type TabsTriggerProps = TabTriggerProps;

export function TabsTrigger({ className, ...props }: TabsTriggerProps) {
  return <TabTrigger className={cn(tabsTriggerBase, className)} {...props} />;
}

export type TabsContentProps = TabContentProps;

export function TabsContent({ className, ...props }: TabsContentProps) {
  return <TabContent className={cn(tabsContentBase, className)} {...props} />;
}

export const useTabs = useTabsContext;

// libs/vortex-svelte/src/tabs/Tabs.svelte
<!-- libs/vortex-svelte/src/tabs/Tabs.svelte -->
<!-- Closely based on: Shark UI tabs (@ark-ui/svelte/tabs), mirrored from @cloudvoyant/vortex-react -->
<script lang="ts">
  import { TabsRoot, type TabsRootProps } from '@ark-ui/svelte/tabs';
  import { tabsRootBase, cn } from '@cloudvoyant/vortex-ui';

  let {
    value,
    defaultValue,
    onValueChange,
    orientation = 'horizontal',
    lazyMount = true,
    unmountOnExit = true,
    class: className = '',
    children,
    ...rest
  }: TabsRootProps = $props();

  const classes = $derived(cn(tabsRootBase, className));
</script>

<TabsRoot {value} {defaultValue} {onValueChange} {orientation} {lazyMount} {unmountOnExit} class={classes} {...rest}>
  {@render children?.()}
</TabsRoot>
